language: java
sudo: false # faster builds
branches:
  only:
  - liu.zhao
jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2
    
install: true

script:
  - travis_wait 30 ./mvnw --batch-mode --no-transfer-progress clean install -DskipTests=false -DskipIntegrationTests=false -Dcheckstyle.skip=false -Drat.skip=false -Dmaven.javadoc.skip=true

after_success:
  - echo "build success!"
  # bash <(curl -s https://codecov.io/bash)  https://github.com/mojohaus/cobertura-maven-plugin/issues/21

after_failure:
  - echo "build failed!"
