language: java
branches:
  only:
  - liu.zhao
jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2

script:
  - travis_wait 30 ./mvnw --batch-mode --no-transfer-progress clean install -DskipTests=false -DskipIntegrationTests=false -Dcheckstyle.skip=false -Drat.skip=false -Dmaven.javadoc.skip=true

after_success:
  - echo "build successed!"

after_failure:
  - echo "build failed!"
