version: "3"
services:
  rd:
    image: redis:5
  db0:
    image: yisiqi/postgres-asciinema:11
    environment:
      - POSTGRES_PASSWORD=aaaaaa
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
  nginx:
    image: nginx:stable
    # 对外使用81端口
    ports:
      - "8080:80"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - core
      - core2
  core:
    image: gdc.docker.iec.io/my-server:liu.zhao-20201205
    environment:
      - SPRING_REDIS_HOST=rd
      - SPRING_REDIS_PORT=6379
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db0:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=aaaaaa
    depends_on:
      - rd
      - db0
  core2:
    image: gdc.docker.iec.io/my-server:liu.zhao-20201205
    environment:
      - SPRING_REDIS_HOST=rd
      - SPRING_REDIS_PORT=6379
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db0:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=aaaaaa
    depends_on:
      - rd
      - db0
